brew "bat"
brew "btop"
brew "ddgr"
brew "eza"
brew "fnm"
brew "fx"
brew "fzf"
brew "glow"
brew "grex"
brew "jq"
brew "lazygit"
brew "mas"
brew "neofetch"
brew "neovim"
brew "rclone"
brew "ripgrep"
brew "starship"
brew "xplr"
brew "zoxide"
brew "zsh"
cask "cloudflare-warp"
cask "iina"
cask "keycastr"
cask "font-symbols-only-nerd-font"
cask "proxyman"
cask "font-sf-mono"
cask "wezterm"
mas "Amphetamine", id: 937984704
mas "djay", id: 450527929
mas "HotKey", id: 975890633
mas "NextDNS", id: 1464122853
